import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { auth } from "./auth";
import Auth from "@/components/Auth";
import Header from "@/components/Header";
import Sidebar from "@/components/Sidebar";
import NextTopLoader from "nextjs-toploader";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await auth();

  if (!session || !session.user) {
    return (
      <html lang="en">
        <body className={inter.className}>
          <Auth />
        </body>
      </html>
    );
  }

  return (
    <html lang="en">
      <body className={inter.className + " p-5"}>
        <NextTopLoader showSpinner={false} />
        <Header />

        <div className="flex gap-5 mt-5 h-[87vh]">
          <Sidebar />
          <div className="border border-slate-600 rounded-lg w-full">
            {children}
          </div>
        </div>
      </body>
    </html>
  );
}
